# Generated by Django 4.0.1 on 2022-02-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
